image: python:3.9

name: catfish

ports:
  8000/tcp: 8000

# Unix: /Users/admin/data/code_project/catfish
# Windows: D:\code-project\catfish
volumes:
  /Users/admin/data/code_project/catfish:
    bind: /path/to/container
    mode: rw

detach: true

command:
  - sh
  - -c
  - "cd /path/to/container && pip install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com&& python manage.py runserver 0.0.0.0:8000"
